### ISSUE TITLE
Error while installing dlib

### ISSUE THREAD

**Issue by vamsireddy22** [saimj7/People-Counting-in-Real-Time#21]
Hey, I got this issue while installing dlib.

Kindly, have a look and let me what to do now!

Thanks in advance.

Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\BHEEMIREDDY VAMSI\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\BHEEMI~1\\AppData\\Local\\Temp\\pip-install-qo355fxk\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\BHEEMI~1\\AppData\\Local\\Temp\\pip-install-qo355fxk\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\BHEEMI~1\AppData\Local\Temp\pip-wheel-f2i2aeom' --python-tag cp37
       cwd: C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\
  Complete output (53 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\setup.py", line 120, in get_cmake_version
      out = subprocess.check_output(['cmake', '--version'])
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\subprocess.py", line 395, in check_output
      **kwargs).stdout
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\subprocess.py", line 472, in run
      with Popen(*popenargs, **kwargs) as process:
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\subprocess.py", line 775, in __init__
      restore_signals, start_new_session)
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
      startupinfo)
  FileNotFoundError: [WinError 2] The system cannot find the file specified

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\setup.py", line 261, in <module>
      'Topic :: Software Development',
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\setup.py", line 129, in run
      cmake_version = self.get_cmake_version()
    File "C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\setup.py", line 125, in get_cmake_version
      "\n*******************************************************************\n")
  RuntimeError:
  *******************************************************************
   CMake must be installed to build the following extensions: dlib
  *******************************************************************

  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib, opencv-python, scipy
  Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\BHEEMIREDDY VAMSI\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\BHEEMI~1\\AppData\\Local\\Temp\\pip-install-qo355fxk\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\BHEEMI~1\\AppData\\Local\\Temp\\pip-install-qo355fxk\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\BHEEMI~1\AppData\Local\Temp\pip-record-zwr430fz\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\
    Complete output (55 lines):
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\BHEEMIREDDY VAMSI\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "C:\Users\BHEEMI~1\AppData\Local\Temp\pip-install-qo355fxk\dlib\setup.py", line 125, in get_cmake_version
        "\n*******************************************************************\n")
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\BHEEMIREDDY VAMSI\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\BHEEMI~1\\AppData\\Local\\Temp\\pip-install-qo355fxk\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\BHEEMI~1\\AppData\\Local\\Temp\\pip-install-qo355fxk\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\BHEEMI~1\AppData\Local\Temp\pip-record-zwr430fz\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by saimj7** [comment]
Hi, you need to install CMake and add its directory to the path environment variable: https://cmake.org/install/

**Comment by vamsireddy22** [comment]
@saimj7  While running on input video, I am getting this error. And it works fine with laptop webcam. 
Kindly, look into this and let me know. 
Thanks in advance.

(env_vamsi) C:\Users\BHEEMIREDDY VAMSI\Desktop\Main-Project>python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4
[INFO] Starting the video..
[ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-m8us58q4\opencv\modules\videoio\src\cap.cpp (162) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-m8us58q4\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file):   in function 'cv::icvExtractPattern'

**Comment by saimj7** [comment]
Can you install the requirements as in `requirements.txt`?

**Comment by vamsireddy22** [comment]
version of opencv-python is 4.5.2.52

but while trying to install version of 4.2.0.32 it results in error! refer below picture

(env_vamsi) C:\Users\BHEEMIREDDY VAMSI\Desktop\Main-Project>pip install opencv-python==4.2.0.32
ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32 (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.14.51, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.2.52)
ERROR: No matching distribution found for opencv-python==4.2.0.32

**Comment by saimj7** [comment]
Weird, I'm able to install it again, are you using anaconda?

**Comment by vamsireddy22** [comment]
Yes :( Initially I tried using cmd, but I got errors then I tried in Anaconda. Kindly help me na!

**Comment by vamsireddy22** [comment]
Yes, now I installed all requirements as per requirements file but I am got this error while running on video input. 
P.S: Running using cmd 
Python version 3.7.4 

C:\Users\BHEEMIREDDY VAMSI\Desktop\Main-Project>python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4
[INFO] Starting the video..
[ERROR:0] global C:\projects\opencv-python\opencv\modules\videoio\src\cap.cpp (116) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file):   in function 'cv::icvExtractPattern'

**Comment by saimj7** [comment]
Let's try to break it down, did you install ffmpeg on windows? Also, did you build OpenCV from scratch?

**Comment by vamsireddy22** [comment]
1. I installed ffmpeg using this command pip install python-ffmpeg
2. No, I did not OpenCV from scratch

**Comment by saimj7** [comment]
Download ffmpeg https://ffmpeg.org/download.html and add its directory to the path.

**Comment by vamsireddy22** [comment]
Done Installed ffmpeg and added to environmental variables. 
P.S : Again same error.

**Comment by saimj7** [comment]
Can you install python and the requirements using anaconda? E.g., https://medium.com/@GalarnykMichael/install-python-anaconda-on-windows-2020-f8e188f9a63d

**Comment by vamsireddy22** [comment]
Yes, bro. Did that. Let me summarize what I did so far!
1. Tried in cmd with python version 3.7.4, installed all requirements. 
2. Tried in anaconda with python version 3.7.4, installed all requirements. 

PS : It is working fine for Webcam.

**Comment by saimj7** [comment]
Can you try this in anaconda? Create a new environment, do `conda insall pip` and then: `pip install dlib==19.22.0 imutils==0.5.4 numpy==1.20.3 opencv-python==4.5.2.52 schedule==0.6.0 scipy==1.6.3`. Python version would be 3.9.5 by default.

**Comment by vamsireddy22** [comment]
Sir, I did everything. In last conversation you said building the opencv from scratch. How can I do that?  

I tried above packages installation on both cmd and anaconda. Got the same error. Something with my OpenCv tobe specific while extracting the patterns. Kindly, go through the below error. 

C:\Users\BHEEMIREDDY VAMSI\Desktop\Main-Project>python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel --input videos/example_01.mp4
[INFO] Starting the video..
[ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-m8us58q4\opencv\modules\videoio\src\cap.cpp (162) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-m8us58q4\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file):   in function 'cv::icvExtractPattern'

**Comment by saimj7** [comment]
Did you create a new Conda environment and do you find the file `opencv_videoio_ffmpeg452_64.dll`?

**Comment by vamsireddy22** [comment]
No, sir. I couldn't found any such file.  How can do it.?

**Comment by saimj7** [comment]
Can I test this myself? Please email me.
