### ISSUE TITLE
real time tracking error

### ISSUE THREAD

**Issue by syedbuzzy** [saimj7/People-Counting-in-Real-Time#27]
this is the error message that im getting..i dont know y

C:\Users\User\Desktop\People-Counting-in-Real-Time-master>python run.py --prototxt mobilenet_ssd/MobileNetSSD_deploy.prototxt --model mobilenet_ssd/MobileNetSSD_deploy.caffemodel
[INFO] Starting the live stream..
Traceback (most recent call last):
  File "C:\Users\User\Desktop\People-Counting-in-Real-Time-master\run.py", line 353, in <module>
    run()
  File "C:\Users\User\Desktop\People-Counting-in-Real-Time-master\run.py", line 100, in run
    frame = imutils.resize(frame, width = 500)
  File "C:\python\lib\site-packages\imutils\convenience.py", line 69, in resize
    (h, w) = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by saimj7** [comment]
Check if you 1. Installed everything as per requirements.txt; 2. Set url = 0 in mylib>config.py if you're on webcam.

**Comment by syedbuzzy** [comment]
problem solved ..thanks sir
