### ISSUE TITLE
sending email alert

### ISSUE THREAD

**Issue by onkararj** [saimj7/People-Counting-in-Real-Time#35]
i have entered my email id in config.py
i am getting following error. thank you in advance

[INFO] Starting the live stream..
[INFO] Sending email alert..
Traceback (most recent call last):
  File "run.py", line 353, in <module>
    run()
  File "run.py", line 244, in run
    Mailer().send(config.MAIL)
  File "C:\Users\onkar\OneDrive\Desktop\be project\People-Counting-in-Real-Time\mylib\mailer.py", line 23, in send
    self.server.login(self.EMAIL, self.PASS)
  File "C:\Users\onkar\anaconda3\envs\env_dlib\lib\smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "C:\Users\onkar\anaconda3\envs\env_dlib\lib\smtplib.py", line 631, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
TypeError: must be str, not bytes

**Comment by saimj7** [comment]
Can I check your mailer.py? But replace your email with something else so I don't have to see it
