### ISSUE TITLE
Pkg-config binary for machine 1 not found. (Error while installing requirements)

### ISSUE THREAD

**Issue by amirrezabsh** [saimj7/People-Counting-in-Real-Time#61]
Hi please have a look in this error which I get it while requirements installation.

Getting requirements to build wheel: finished with status 'error'

2023-05-17 20:06:29.128 [info]   error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]
      + meson setup --native-file=C:\Users\NoteBook\AppData\Local\Temp\pip-install-992tyj1w\scipy_64243345752f4af9b822e71970810492\.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0 C:\Users\NoteBook\AppData\Local\Temp\pip-install-992tyj1w\scipy_64243345752f4af9b822e71970810492 C:\Users\NoteBook\AppData\Local\Temp\pip-install-992tyj1w\scipy_64243345752f4af9b822e71970810492\.mesonpy-i8_oauep\build
      The Meson build system
      Version: 0.62.2
  
2023-05-17 20:06:29.128 [info]     Source dir: C:\Users\NoteBook\AppData\Local\Temp\pip-install-992tyj1w\scipy_64243345752f4af9b822e71970810492
      Build dir: C:\Users\NoteBook\AppData\Local\Temp\pip-install-992tyj1w\scipy_64243345752f4af9b822e71970810492\.mesonpy-i8_oauep\build
      Build type: native build
      Project name: SciPy
      Project version: 1.9.0
      C compiler for the host machine: gcc (gcc 8.3.0 "gcc (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0")
      C linker for the host machine: gcc ld.bfd 2.32
      C++ compiler for the host machine: c++ (gcc 8.3.0 "c++ (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0")
      C++ linker for the host machine: c++ ld.bfd 2.32
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Compiler for C supports arguments -Wno-unused-but-set-variable: YES
      Library m found: YES
      Fortran compiler for the host machine: gfortran (gcc 8.3.0 "GNU Fortran (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0")
      Fortran linker for the host machine: gfortran ld.bfd 2.32
      Program cython found: YES (C:\Users\NoteBook\AppData\Local\Temp\pip-build-env-v0o2ajia\overlay\Scripts\cython.EXE)
      Program pythran found: YES (C:\Users\NoteBook\AppData\Local\Temp\pip-build-env-v0o2ajia\overlay\Scripts\pythran.EXE)
      Program scipy/_build_utils/copyfiles.py found: YES (e:\People-Counting-in-Real-Time-master\.venv\Scripts\python.exe C:\Users\NoteBook\AppData\Local\Temp\pip-install-992tyj1w\scipy_64243345752f4af9b822e71970810492\scipy/_build_utils/copyfiles.py)
      Program python3 found: YES (e:\People-Counting-in-Real-Time-master\.venv\Scripts\python.exe)
      WARNING: You should add the boolean check kwarg to the run_command call.
               It currently defaults to false,
  
2023-05-17 20:06:29.128 [info]              but it will default to true in future releases of meson.
               See also: https://github.com/mesonbuild/meson/issues/9300
      Library npymath found: YES
      Library npyrandom found: YES
      found pkg-config 'C:\\Strawberry\\perl\\bin\\pkg-config.BAT' but it is Strawberry Perl and thus broken. Ignoring...
      Found Pkg-config: NO
      Found CMake: C:\Program Files\CMake\bin\cmake.EXE (3.26.3)
2023-05-17 20:06:29.129 [info] 
      Run-time dependency openblas found: NO (tried cmake)
      
      ..\..\scipy\meson.build:120:0: ERROR: Pkg-config binary for machine 1 not found. Giving up.
      
      A full log can be found at C:\Users\NoteBook\AppData\Local\Temp\pip-install-992tyj1w\scipy_64243345752f4af9b822e71970810492\.mesonpy-i8_oauep\build\meson-logs\meson-log.txt
      Traceback (most recent call last):
        File "e:\People-Counting-in-Real-Time-master\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
     
2023-05-17 20:06:29.129 [info]      main()
        File "e:\People-Counting-in-Real-Time-master\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "e:\People-Counting-in-Real-Time-master\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\NoteBook\AppData\Local\Temp\pip-build-env-v0o2ajia\overlay\Lib\site-packages\mesonpy\__init__.py", line 909, in get_requires_for_build_wheel
     
2023-05-17 20:06:29.129 [info]      with _project(config_settings) as project:
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
        File "C:\Users\NoteBook\AppData\Local\Temp\pip-build-env-v0o2ajia\overlay\Lib\site-packages\mesonpy\__init__.py", line 888, in _project
          with Project.with_temp_working_dir(
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 137, in __enter__
          return next(self.gen)
                 ^^^^^^^^^^^^^^
      
2023-05-17 20:06:29.129 [info]   File "C:\Users\NoteBook\AppData\Local\Temp\pip-build-env-v0o2ajia\overlay\Lib\site-packages\mesonpy\__init__.py", line 547, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\NoteBook\AppData\Local\Temp\pip-build-env-v0o2ajia\overlay\Lib\site-packages\mesonpy\__init__.py", line 463, in __init__
          self._configure(reconfigure=bool(build_dir) and not native_file_mismatch)
        File "C:\Users\NoteBook\AppData\Local\Temp\pip-build-env-v0o2ajia\overlay\Lib\site-packages\mesonpy\__init__.py", line 494, in _configure
          self._meson(
        File "C:\Users\NoteBook\AppData\Local\Temp\pip-build-env-v0o2ajia\overlay\Lib\site-packages\mesonpy\__init__.py", line 477, in _meson
          return self._proc('meson', *args)
      
2023-05-17 20:06:29.130 [info]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\NoteBook\AppData\Local\Temp\pip-build-env-v0o2ajia\overlay\Lib\site-packages\mesonpy\__init__.py", line 472, in _proc
          subprocess.check_call(list(args))
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'setup', '--native-file=C:\\Users\\NoteBook\\AppData\\Local\\Temp\\pip-install-992tyj1w\\scipy_64243345752f4af9b822e71970810492\\.mesonpy-native-file.ini', '-Ddebug=false', '-Doptimization=2', '--prefix=C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0', 'C:\\Users\\NoteBook\\AppData\\Local\\Temp\\pip-install-992tyj1w\\scipy_64243345752f4af9b822e71970810492', 'C:\\Users\\NoteBook\\AppData\\Local\\Temp\\pip-install-992tyj1w\\scipy_64243345752f4af9b822e71970810492\\.mesonpy-i8_oauep\\build']' returned non-zero exit status 1.
      [end of output]
  
  
2023-05-17 20:06:29.130 [info] note: This error originates from a subprocess, and is likely not a problem with pip.

2023-05-17 20:06:29.132 [info] error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

2023-05-17 20:06:35.279 [info] Traceback (most recent call last):
  File "c:\Users\NoteBook\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\create_venv.py", line 77, in run_process

2023-05-17 20:06:35.279 [info]     subprocess.run(args, cwd=os.getcwd(), check=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 571, in run

2023-05-17 20:06:35.279 [info]     raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['e:\\People-Counting-in-Real-Time-master\\.venv\\Scripts\\python.exe', '-m', 'pip', 'install', '-r', 'e:\\People-Counting-in-Real-Time-master\\requirements.txt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\NoteBook\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\create_venv.py", line 232, in <module>

2023-05-17 20:06:35.279 [info]     main(sys.argv[1:])

2023-05-17 20:06:35.280 [info]   File "c:\Users\NoteBook\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\create_venv.py", line 228, in main

2023-05-17 20:06:35.280 [info]     install_requirements(venv_path, args.requirements)
  File "c:\Users\NoteBook\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\create_venv.py", line 97, in install_requirements

2023-05-17 20:06:35.280 [info]     run_process(
  File "c:\Users\NoteBook\.vscode\extensions\ms-python.python-2023.8.0\pythonFiles\create_venv.py", line 79, in run_process

2023-05-17 20:06:35.281 [info]     raise VenvError(error_message)
VenvError: CREATE_VENV.PIP_FAILED_INSTALL_REQUIREMENTS

2023-05-17 20:06:35.298 [error] Error while running venv creation script:  CREATE_VENV.PIP_FAILED_INSTALL_REQUIREMENTS
2023-05-17 20:06:35.298 [error] CREATE_VENV.PIP_FAILED_INSTALL_REQUIREMENTS

**Comment by eli-schwartz** [comment]
Please see https://scipy.org/install/

This project depends on SciPy: https://github.com/saimj7/People-Counting-in-Real-Time/blob/8d807b339e4164e79589004cd2b4f27553a81869/requirements.txt#L7

SciPy documents that building from source "can be a nontrivial exercise. We recommend using binaries instead if those are available for your platform".

This is especially challenging on Windows. You should try to see if you can find wheels for your CPU architecture and python version: https://pypi.org/project/scipy/#files

**Comment by amirrezabsh** [comment]
> Please see https://scipy.org/install/
> 
> This project depends on SciPy:
> 
> https://github.com/saimj7/People-Counting-in-Real-Time/blob/8d807b339e4164e79589004cd2b4f27553a81869/requirements.txt#L7
> 
> SciPy documents that building from source "can be a nontrivial exercise. We recommend using binaries instead if those are available for your platform".
> 
> This is especially challenging on Windows. You should try to see if you can find wheels for your CPU architecture and python version: https://pypi.org/project/scipy/#files

the problem is that it gives me this "no matching version for SciPy 1.8.0" error. So I tried 1.9.0 version instead and my platform is windows. but you said that it is challenging on windows, so if I try it on ubuntu it will there be any problem?

**Comment by eli-schwartz** [comment]
On Ubuntu it is relatively a lot easier, because there's a very simple copy/paste command to apt install everything you need: https://scipy.github.io/devdocs/dev/contributor/building.html#system-level-dependencies

**Comment by saimj7** [comment]
@amirrezabsh Thanks for pointing it out, updated the ```requirements.txt``` after resolving some version conflicts. Note that the required Python version is ```3.11.3```

Could you give it a try?

**Comment by amirrezabsh** [comment]
@saimj7  It solved the problem. Thanks!
